baseurl: /
languageCode: en-us
title: FITE7001 MSc(FTDA) Project [2023/24]
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents:   ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/ 

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1 
    - name: "Milestones"
      url: "/Milestones/" 
      weight: 2
    - name: "Categories"  
      url: "/categories/"
      weight: 3
    - name: "Code"
      url: "/code/" 
      weight: 4
    - name: "Reference"
      url: "/Reference/"
      weight: 5
    - name: "About"
      url: "/About/"  

params:
  description: "The Potential Paths of RegTech to Solve the Pain Points and Facilitate CDD/AML Process"
  footer: " "
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
